In [1]:
import pandas as pd
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", 200)
df=pd.read_csv("decisions_data_structured.csv")
df.head(2)

,id_filename,decision_sign,name,party,legal area,entscheid
0,1000,5A_449/2026,Bovey,FDP,Zivilrecht,nicht eingetreten
1,1001,2E_8/2024,Aubry Girardin,Grüne,AndererBereich,abgewiesen

## Cosideration of decisions made by 5 judges.

In [2]:
richter_pro_urteil = df.groupby("decision_sign").size()

fuenfer_urteile = richter_pro_urteil[
    richter_pro_urteil == 5
].index

df_5 = df[df["decision_sign"].isin(fuenfer_urteile)]

total_number_decicion_with_5_judges = len(fuenfer_urteile)

print("Total number of decisions with 5 Judges: "+ str(total_number_decicion_with_5_judges))

Total number of decisions with 5 Judges: 166

 ### 1.Comparision between decisions of left- and right-wing-judge-teams
* right-wing-judgeteam = at least 2 right-wing-judges (SP or Grüne)
* right-wing-judgeteam = at least 2 right-wing-judges (SVP or FDP)

#### **1a) Comparisen over all legal areas**

In [3]:
# 1. Pro Urteil zählen, wie viele Richter SVP oder FDP sind
right_major = (df_5["party"].isin(["SVP", "FDP"]).groupby(df_5["decision_sign"]).sum()>= 3)
left_major = (df_5["party"].isin(["SP", "Grüne"]).groupby(df_5["decision_sign"]).sum()>= 3)
center_major = (df_5["party"].isin(["Die Mitte", "GLP"]).groupby(df_5["decision_sign"]).sum() >= 3)

center_right_major = (df_5["party"].isin(["SVP", "FDP", "Die Mitte", "GLP"]).groupby(df_5["decision_sign"]).sum()>= 3)
center_left_major = (df_5["party"].isin(["SP", "Grüne", "Die Mitte", "GLP"]).groupby(df_5["decision_sign"]).sum()>= 3)


without_right = (df_5["party"].isin(["FDP", "SVP"]).groupby(df_5["decision_sign"]).sum() == 0)
without_left = (df_5["party"].isin(["SP", "Grüne"]).groupby(df_5["decision_sign"]).sum() == 0)

# 2. Nur die Urteile mit rechter Mehrheit herausnehmen
right_wing_decisions = right_major[right_major].index
left_wing_decisions = left_major[left_major].index
center_decisions = center_major[center_major].index

center_right_decisions = center_right_major.index
center_left_decisions = center_left_major.index

without_right_decisions = without_left[without_left].index
without_left_decisions = without_left[without_left].index

# 5. Von diesen Urteilen zählen, wie viele gutgeheissen
# oder teilweise gutgeheissen wurden
number_appeal_success_right = df_5[df_5["decision_sign"].isin(right_wing_decisions)& df_5["entscheid"].isin(["gutgeheissen","teilweise gutgeheissen"])]["decision_sign"].nunique()
number_appeal_success_left = df_5[df_5["decision_sign"].isin(left_wing_decisions)& df_5["entscheid"].isin(["gutgeheissen","teilweise gutgeheissen"])]["decision_sign"].nunique()
number_appeal_success_center = df_5[df_5["decision_sign"].isin(center_decisions)& df_5["entscheid"].isin(["gutgeheissen", "teilweise gutgeheissen"])]["decision_sign"].nunique()

# Calculate all variables
total_number_decicion_with_5_judges = len(df_5) / 5

anzahl_right_wing_decisions = right_major.sum()
anzahl_left_wing_decisions = left_major.sum()
anzahl_center_decisions = center_major.sum()
anzahl_center_right_decisions = center_right_major.sum()
anzahl_center_left_decisions = center_left_major.sum()
anzahl_without_right_decisions = without_right.sum()
anzahl_without_left_decisions = without_left.sum()

print("NUMBERS OF DECISIONS")
print("total_5-judge-panel-decisions: " + str(total_number_decicion_with_5_judges))

print("How 5-judge-decisions are made-------------------------")
print("Right-wing decisions:", anzahl_right_wing_decisions)
print("Left-wing decisions:", anzahl_left_wing_decisions)
print("Center decisions:", anzahl_center_decisions)
print("Center-right decisions:", anzahl_center_right_decisions)
print("Center-left decisions:", anzahl_center_left_decisions)
print("Decisions without right:", anzahl_without_right_decisions)
print("Decisions without left:", anzahl_without_left_decisions)

NUMBERS OF DECISIONS
total_5-judge-panel-decisions: 166.0
How 5-judge-decisions are made-------------------------
Right-wing decisions: 35
Left-wing decisions: 14
Center decisions: 0
Center-right decisions: 115
Center-left decisions: 102
Decisions without right: 1
Decisions without left: 1

## Nummern und Namen zu 5er-decisions ohne linke Richter

In [4]:
left_decisions = without_left[without_left].index

# Alle Zeilen dieser Urteile mit sämtlichen Spalten
df_without_left = df_5[df_5["decision_sign"].isin(left_decisions)].sort_values("decision_sign")

df_without_left

,id_filename,decision_sign,name,party,legal area,entscheid
521,1529,6B_942/2025,Muschietti,FDP,Strafrecht,gutgeheissen
2701,1529,6B_942/2025,Rüedi,SVP,Strafrecht,gutgeheissen
4370,1529,6B_942/2025,von Felten,Die Mitte,Strafrecht,gutgeheissen
5592,1529,6B_942/2025,Guidon,SVP,Strafrecht,gutgeheissen
5785,1529,6B_942/2025,Glassey,Die Mitte,Strafrecht,gutgeheissen

## Nummern und Namen zu 5er-decisions ohne rechte Richter

In [5]:
right_decisions = without_right[without_right].index

# Alle Zeilen dieser Urteile mit sämtlichen Spalten
df_without_right = df_5[df_5["decision_sign"].isin(right_decisions)].sort_values("decision_sign")

df_without_right

,id_filename,decision_sign,name,party,legal area,entscheid
1697,42,"2C_31/2025, 2C_34/2025",Aubry Girardin,Grüne,Öffentliches Recht,abgewiesen
3587,42,"2C_31/2025, 2C_34/2025",Donzallaz,parteilos (ex SVP),Öffentliches Recht,abgewiesen
5171,42,"2C_31/2025, 2C_34/2025",Hänni,Die Mitte,Öffentliches Recht,abgewiesen
5689,42,"2C_31/2025, 2C_34/2025",Ryter,SP,Öffentliches Recht,abgewiesen
5864,42,"2C_31/2025, 2C_34/2025",Petrik-Haltiner,SP,Öffentliches Recht,abgewiesen

In [6]:
total_number_decicion_with_5_judges = len(df_5) / 5

anzahl_right_wing_decisions = right_major.sum()
anzahl_left_wing_decisions = left_major.sum()
anzahl_center_decisions = center_major.sum()
anzahl_center_right_decisions = center_right_major.sum()
anzahl_center_left_decisions = center_left_major.sum()
anzahl_without_right_decisions = without_right.sum()
anzahl_without_left_decisions = without_left.sum()








result_decisions_5judge=[

 {"composition":"total", "number":total_number_decicion_with_5_judges}, 


{"composition":"center_right-majority", "number":anzahl_center_right_decisions},
{"composition":"center_left-majority", "number":anzahl_center_left_decisions}, 

 {"composition":"right-wing-majority", "number":anzahl_right_wing_decisions},
 {"composition":"left-wing-majority", "number":anzahl_left_wing_decisions}, 
{"composition":"without left judges", "number":anzahl_without_left_decisions}, 
{"composition":"without right judges", "number":anzahl_without_right_decisions}, 
]

result_5judge_decisions=pd.DataFrame(result_decisions_5judge)


result_5judge_decisions.to_excel("results/5judge_decisions.xlsx", index=False)

#### **1b) Comparisen only Strafrecht (=Criminal Cases)**

In [7]:
df_5_strafrecht=df_5[df_5["legal area"]=="Strafrecht"]

In [8]:
# 1. Pro Urteil zählen, wie viele Richter SVP oder FDP sind
right_major = (df_5["party"].isin(["SVP", "FDP"]).groupby(df_5["decision_sign"]).sum()>= 3)
left_major = (df_5["party"].isin(["SP", "Grüne"]).groupby(df_5["decision_sign"]).sum()>= 3)
center_major = (df_5["party"].isin(["Die Mitte", "GLP"]).groupby(df_5["decision_sign"]).sum() >= 3)

# 2. Nur die Urteile mit rechter Mehrheit herausnehmen
right_wing_decisions = right_major[right_major].index
left_wing_decisions = left_major[left_major].index
center_decisions = center_major[center_major].index

# 5. Von diesen Urteilen zählen, wie viele gutgeheissen
# oder teilweise gutgeheissen wurden
number_appeal_success_right = df_5[df_5["decision_sign"].isin(right_wing_decisions)& df_5["entscheid"].isin(["gutgeheissen","teilweise gutgeheissen"])]["decision_sign"].nunique()
number_appeal_success_left = df_5[df_5["decision_sign"].isin(left_wing_decisions)& df_5["entscheid"].isin(["gutgeheissen","teilweise gutgeheissen"])]["decision_sign"].nunique()
number_appeal_success_center = df_5[df_5["decision_sign"].isin(center_decisions)& df_5["entscheid"].isin(["gutgeheissen", "teilweise gutgeheissen"])]["decision_sign"].nunique()

# Calculate all variables
total_number_decicion_with_5_judges = len(df_5) / 5
anzahl_right_wing_decisions = right_major.sum()
anzahl_left_wing_decisions = left_major.sum()
anzahl_center_decisions = center_major.sum()
# 1. Pro Urteil zählen, wie viele Richter SVP oder FDP sind
right_major_crim = (df_5_strafrecht["party"].isin(["SVP", "FDP"]).groupby(df_5_strafrecht["decision_sign"]).sum()>= 2)
left_major_crim = (df_5_strafrecht["party"].isin(["SP", "Grüne"]).groupby(df_5_strafrecht["decision_sign"]).sum()>= 2)
center_major_crim = (df_5_strafrecht["party"].isin(["Die Mitte", "GLP"]).groupby(df_5_strafrecht["decision_sign"]).sum()>= 2)

number_appeal_success_right_crim = df_5_strafrecht[df_5_strafrecht["decision_sign"].isin(right_wing_decisions)& df_5_strafrecht["entscheid"].isin(["gutgeheissen","teilweise gutgeheissen"])]["decision_sign"].nunique()
number_appeal_success_left_crim = df_5_strafrecht[df_5_strafrecht["decision_sign"].isin(left_wing_decisions)& df_5_strafrecht["entscheid"].isin(["gutgeheissen","teilweise gutgeheissen"])]["decision_sign"].nunique()
number_appeal_success_center_crim = df_5_strafrecht[df_5_strafrecht["decision_sign"].isin(center_decisions)& df_5_strafrecht["entscheid"].isin(["gutgeheissen","teilweise gutgeheissen"])]["decision_sign"].nunique()

anzahl_right_wing_decisions_crim = right_major_crim.sum()
anzahl_left_wing_decisions_crim = left_major_crim.sum()
anzahl_center_decisions_crim = center_major_crim.sum()

prercent_right_wing_crim = (number_appeal_success_right_crim / anzahl_right_wing_decisions_crim* 100)
prercent_left_wing_crim = (number_appeal_success_left_crim / anzahl_left_wing_decisions_crim * 100)
prercent_center_crim = (number_appeal_success_center_crim / anzahl_center_decisions_crim * 100)

print("ONLY CRIMINAL CASES, ONLY 5-JUDGE TEAMS:")
print("Number of rightwing_decisions: " +str(anzahl_right_wing_decisions_crim))
print("Number of leftwing_decisions: " +str(anzahl_left_wing_decisions_crim))
print("Number of center_decisions: " +str(anzahl_center_decisions_crim))

print("Number of success with right majority: " + str(number_appeal_success_right_crim))
print("Number of success with left majority: " + str(number_appeal_success_left_crim))
print("Number of success with center majority: " + str(number_appeal_success_center_crim))

print(f"Success-rate with a right-wing-majority: {prercent_right_wing_crim:.1f}%")
print(f"Success-rate with a left-wing-majority: {prercent_left_wing_crim:.1f}%")
print(f"Success-rate with a center-majority: {prercent_center_crim:.1f}%")

ONLY CRIMINAL CASES, ONLY 5-JUDGE TEAMS:
Number of rightwing_decisions: 22
Number of leftwing_decisions: 14
Number of center_decisions: 19
Number of success with right majority: 1
Number of success with left majority: 9
Number of success with center majority: 0
Success-rate with a right-wing-majority: 4.5%
Success-rate with a left-wing-majority: 64.3%
Success-rate with a center-majority: 0.0%

#### **1b) Comparisen only Öffentliches Recht ( = public law )**

In [9]:
df_5_oeffrecht=df_5[df_5["legal area"]=="Öffentliches Recht"]

In [10]:
# 1. Pro Urteil zählen, wie viele Richter SVP oder FDP sind
right_major_publaw = (df_5_oeffrecht["party"].isin(["SVP", "FDP"]).groupby(df_5_oeffrecht["decision_sign"]).sum()>= 3)
left_major_publaw = (df_5_oeffrecht["party"].isin(["SP", "Grüne"]).groupby(df_5_oeffrecht["decision_sign"]).sum()>= 3)
center_major_publaw = (df_5_oeffrecht["party"].isin(["Die Mitte", "GLP"]).groupby(df_5_oeffrecht["decision_sign"]).sum()>= 3)


# 5. Von diesen Urteilen zählen, wie viele gutgeheissen
# oder teilweise gutgeheissen wurden
number_appeal_success_right_publaw = df_5_oeffrecht[df_5_oeffrecht["decision_sign"].isin(right_wing_decisions)& df_5_oeffrecht["entscheid"].isin(["gutgeheissen","teilweise gutgeheissen"])]["decision_sign"].nunique()
number_appeal_success_left_publaw = df_5_oeffrecht[df_5_oeffrecht["decision_sign"].isin(left_wing_decisions)& df_5_oeffrecht["entscheid"].isin(["gutgeheissen","teilweise gutgeheissen"])]["decision_sign"].nunique()
number_appeal_success_center_publaw = df_5_oeffrecht[df_5_oeffrecht["decision_sign"].isin(center_decisions)& df_5_oeffrecht["entscheid"].isin(["gutgeheissen","teilweise gutgeheissen"])]["decision_sign"].nunique()

#Total Number of decision made with left_wing-major und with right_wing_major
anzahl_right_wing_decisions_publaw = right_major_publaw.sum()
anzahl_left_wing_decisions_publaw = left_major_publaw.sum()
anzahl_center_decisions_publaw = center_major_publaw.sum()

prercent_right_wing_publaw = ( number_appeal_success_right_publaw / anzahl_right_wing_decisions_publaw * 100)
prercent_left_wing_publaw = (number_appeal_success_left_publaw / anzahl_left_wing_decisions_publaw * 100)
prercent_center_publaw = (number_appeal_success_center_publaw / anzahl_center_decisions_publaw * 100)



print("Number of rightwing_decisions: " +str(anzahl_right_wing_decisions_publaw))
print("Number of leftwing_decisions: " +str(anzahl_left_wing_decisions_publaw))
print("Number of center_decisions: " +str(anzahl_center_decisions_publaw))

print("Number of success with right majority: " + str(number_appeal_success_right_publaw))
print("Number of success with left majority: " + str(number_appeal_success_left_publaw))
print("Number of success with center majority: " + str(number_appeal_success_center_publaw))

print(f"Successrate  with a right-wing-majority {prercent_right_wing_publaw:.1f}%")
print(f"Successrate with left-wing-majority: {prercent_left_wing_publaw:.1f}%")
print(f"Successrate with center-majority: {prercent_center_publaw:.1f}%")

Number of rightwing_decisions: 20
Number of leftwing_decisions: 1
Number of center_decisions: 0
Number of success with right majority: 11
Number of success with left majority: 0
Number of success with center majority: 0
Successrate  with a right-wing-majority 55.0%
Successrate with left-wing-majority: 0.0%
Successrate with center-majority: nan%

C:\Users\misch\AppData\Local\Temp\ipykernel_9768\4070656346.py:20: RuntimeWarning: invalid value encountered in scalar divide
  prercent_center_publaw = (number_appeal_success_center_publaw / anzahl_center_decisions_publaw * 100)

#### **1c) Comparisen only Zivilrecht ( = civil law)**

In [11]:
df_5_zivilrecht=df_5[df_5["legal area"]=="Zivilrecht"]

In [12]:
# 1. Pro Urteil zählen, wie viele Richter SVP oder FDP sind
right_major_zivlaw = (df_5_zivilrecht["party"].isin(["SVP", "FDP"]).groupby(df_5_zivilrecht["decision_sign"]).sum()>= 3)
left_major_zivlaw = (df_5_zivilrecht["party"].isin(["SP", "Grüne"]).groupby(df_5_zivilrecht["decision_sign"]).sum()>= 3)
center_major_zivlaw = (df_5_zivilrecht["party"].isin(["Die Mitte", "GLP"]).groupby(df_5_zivilrecht["decision_sign"]).sum()>= 2)

# 5. Von diesen Urteilen zählen, wie viele gutgeheissen
# oder teilweise gutgeheissen wurden
number_appeal_success_right_zivlaw = df_5_zivilrecht[df_5_zivilrecht["decision_sign"].isin(right_wing_decisions)& df_5_zivilrecht["entscheid"].isin(["gutgeheissen","teilweise gutgeheissen"])]["decision_sign"].nunique()
number_appeal_success_left_zivlaw = df_5_zivilrecht[df_5_zivilrecht["decision_sign"].isin(left_wing_decisions)& df_5_zivilrecht["entscheid"].isin(["gutgeheissen","teilweise gutgeheissen"])]["decision_sign"].nunique()
number_appeal_success_center_zivlaw = df_5_zivilrecht[df_5_zivilrecht["decision_sign"].isin(center_decisions)& df_5_zivilrecht["entscheid"].isin(["gutgeheissen","teilweise gutgeheissen"])]["decision_sign"].nunique()

#Total Number of decision made with left_wing-major und with right_wing_major
anzahl_right_wing_decisions_zivlaw = right_major_zivlaw.sum()
anzahl_left_wing_decisions_zivlaw = left_major_zivlaw.sum()
anzahl_center_decisions_zivlaw = center_major_zivlaw.sum()

anzahl_left_wing_decisions_zivlaw = left_major_zivlaw.sum()
prercent_right_wing_zivlaw = (number_appeal_success_right_zivlaw/ anzahl_right_wing_decisions_zivlaw* 100)
prercent_left_wing_zivlaw = (number_appeal_success_left_zivlaw/ anzahl_left_wing_decisions_zivlaw* 100)
prercent_center_zivlaw = (number_appeal_success_left_zivlaw/ anzahl_center_decisions_zivlaw* 100)

print("Number of rightwing_decision: " +str(anzahl_right_wing_decisions_zivlaw))
print("Number of leftwing_decision: " +str(anzahl_left_wing_decisions_zivlaw))
print("Number of center_decision: " +str(anzahl_center_decisions_zivlaw))

print("Number of success with right majority: " + str(number_appeal_success_right_zivlaw))
print("Number of success with left majority: " + str(number_appeal_success_left_zivlaw))
print("Number of success with center majority: " + str(number_appeal_success_center_zivlaw))

print(f"Success-rate with right-wing-majority: {prercent_right_wing_zivlaw:.1f}%")
print(f"Success-rate with left-wing-majority: {prercent_left_wing_zivlaw:.1f}%")
print(f"Success-rate with center-majority: {prercent_center_zivlaw:.1f}%")

Number of rightwing_decision: 14
Number of leftwing_decision: 0
Number of center_decision: 20
Number of success with right majority: 8
Number of success with left majority: 0
Number of success with center majority: 0
Success-rate with right-wing-majority: 57.1%
Success-rate with left-wing-majority: nan%
Success-rate with center-majority: 0.0%

C:\Users\misch\AppData\Local\Temp\ipykernel_9768\363621388.py:19: RuntimeWarning: invalid value encountered in scalar divide
  prercent_left_wing_zivlaw = (number_appeal_success_left_zivlaw/ anzahl_left_wing_decisions_zivlaw* 100)

In [13]:
results_5crim= [
{"wing":"right-wing", "decisions":anzahl_right_wing_decisions_crim, "numb_success": number_appeal_success_right_crim, "successrate":prercent_right_wing_crim},
{"wing":"left-wing", "decisions":anzahl_left_wing_decisions_crim, "numb_success": number_appeal_success_left_crim, "successrate":prercent_left_wing_crim},  
{"wing":"center", "decisions":anzahl_center_decisions_crim, "numb_success": number_appeal_success_center_crim, "successrate":prercent_center_crim} 
]

df_5er_crim = pd.DataFrame(results_5crim)


df_5er_crim.to_excel("results/5er_crimelaw.xlsx", index=False)

In [14]:
results_5publaw= [
{"wing":"right-wing", "decisions":anzahl_right_wing_decisions_publaw, "numb_success": number_appeal_success_right_publaw, "successrate":prercent_right_wing_publaw},
{"wing":"left-wing", "decisions":anzahl_left_wing_decisions_publaw, "numb_success": number_appeal_success_left_publaw, "successrate":prercent_left_wing_publaw},  
{"wing":"center", "decisions":anzahl_center_decisions_publaw, "numb_success": number_appeal_success_center_publaw, "successrate":prercent_center_publaw} 
]

df_5er_publaw = pd.DataFrame(results_5publaw)


df_5er_publaw.to_excel("results/5er_publaw.xlsx", index=False)

In [15]:
results_5zivlaw= [
{"wing":"right-wing", "decisions":anzahl_right_wing_decisions_zivlaw, "numb_success": number_appeal_success_right_zivlaw, "successrate":prercent_right_wing_zivlaw},
{"wing":"left-wing", "decisions":anzahl_left_wing_decisions_zivlaw, "numb_success": number_appeal_success_left_zivlaw, "successrate":prercent_left_wing_zivlaw},  
{"wing":"center", "decisions":anzahl_center_decisions_zivlaw, "numb_success": number_appeal_success_center_zivlaw, "successrate":prercent_center_zivlaw} 
]

df_5er_zivlaw = pd.DataFrame(results_5zivlaw)


df_5er_zivlaw.to_excel("results/5er_zivlaw.xlsx", index=False)

In [16]:
# judge_total = df.groupby("name").size()
# df_success = df[df["entscheid"].isin(["gutgeheissen", "teilweise gutgeheissen"])]
# judge_success = df_success.groupby("name").size()
# success_rate = judge_success / judge_total * 100
# success_rate.sort_values(ascending=False)

# result = pd.DataFrame({
#     "success_rate": success_rate,
#     "total_decisions": judge_total
# })

# result.sort_values("success_rate", ascending=False)